
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: userburguer
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: burguer_api
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
