spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/userBurguer
    username: root
    password: ${DB_PASSWORD:senha_padrao}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
